### ISSUE TITLE
Feedbacks from TA

### ISSUE THREAD

**Issue by wenwangcode** [WendyMunmunWang/timeseries443#3]
Hey guys, so I went to the TA hour today. After I explained him our project details, he gave me some useful recommendations: 
- Model is too easy
  Since after taking the first difference, the ACF and PACF do not show any significant values.  One way we can do for the model is to use ARIMA (0,0,0)x(0,1,0)_0. But I feel like the model is too easy like that - which shouldn't be.
- Don't take daily data
  Usually for stocks, people don't take daily data. Instead, they take weekly, monthly or yearly datas. I think it is because if we take daily data, the variation is too big. In our case, he recommended we could take the data on every Friday.
- The Range is too small 
  The range of 3 months is too small, even for the daily data. We should take the dataset from at least a few years.
- Use ratios as our data
  For example, if we use weekly data. 
  1_Friday = x
  2_Friday = y
  The data would be: log(x/y) + 100

Reasons:
Using x/y so that we know the associations between two weeks
Using log so that we can have it from negative infinity to positive infinity. 
Using + 100 is optional

What do you guys think?

**Comment by ceciliarong** [comment]
Great ideas. Thanks obtaining all these excellent thinkings from the TA.

Doing the ratio analysis do make our report richer. And probablaly, we can has a section of comparing in our report,  comparing our models analysing the ratio data with the model on first differencing, if both of them give us some significant pratical meanings. 

P.S. I like the idea of using Friday data over several years, as well.
