### ISSUE TITLE
sp.ts statements 

### ISSUE THREAD

**Issue by wenwangcode** [WendyMunmunWang/timeseries443#4]
Hey Cecilia,
I am not sure which one I should use:
sp.ts <- ts(rev(spdata$Adj.Close), start = c(1990,01,03), end = c(2016,03,14))
sp.ts <- ts(rev(spdata$Adj.Close))

If I use the first one, pacf and acf do not have significant values

But if I use the second one, pacf and acf have significant values

**Comment by ceciliarong** [comment]
Hey Wendy,

I think the reason is that the " start = c(1990,01,03), end = c(2016,03,14)) " can be included only when the data in the 1st argument is a matrix, but in our case, spdata$Adj.Close only gives us a column vecor. 

It seems we should use:  sp.ts <- ts(rev(spdata$Adj.Close)) : )

**Comment by wenwangcode** [comment]
Oh i see, thanks!!
