### ISSUE TITLE
Models with Positive and Negative AIC Values

### ISSUE THREAD

**Issue by ceciliarong** [WendyMunmunWang/timeseries443#6]
It seems that one of our models has a positive AIC, and the other one has a negative AIC.

Do you guys know how to compare our two models?

**Comment by wenwangcode** [comment]
I think AIC is the smaller the better, so I assume the negative AIC is better?

**Comment by lion-hearted-achilles** [comment]
Yes, that's right. It's okay for the AIC to be positive or negative, but the smallest AIC value indicates the best model.

**Comment by ceciliarong** [comment]
Ok I see. Thanks!
