### ISSUE TITLE
Meeting tomorrow

### ISSUE THREAD

**Issue by lion-hearted-achilles** [WendyMunmunWang/timeseries443#8]
Hey,
Can we meet altogether some time tomorrow? It would be good to make a few final decisions on the project. It's looking good so far but I just want to touch base. Is everyone free after lab for 15-30 minutes?

**Comment by lion-hearted-achilles** [comment]
After talking with everyone, we're all free to meet after the lab today.

**Comment by wenwangcode** [comment]
Sounds good, see you all soon :)

On Monday, April 4, 2016, Geoff G. Roeder notifications@github.com wrote:

> After talking with everyone, we're all free to meet after the lab today.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/WendyMunmunWang/timeseries443/issues/8#issuecomment-205416539

## 

Sent from Gmail Mobile
